package com.zinios.dealab.models;
// Generated Oct 25, 2018 2:43:44 PM by Hibernate Tools 3.6.0

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name = "admin", catalog = "dealab_db", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
public class Admin implements java.io.Serializable {

	private Integer id;
	private String name;
	private String email;
	private String password;
	private String imageUrl;
	private String token;

	public Admin() {
	}

	public Admin(String email) {
		this.email = email;
	}

	public Admin(String name, String email, String password, String imageUrl, String token) {
		this.name = name;
		this.email = email;
		this.password = password;
		this.imageUrl = imageUrl;
		this.token = token;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 1000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "image_url", length = 2000)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "token", length = 2000)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
