package com.zinios.dealab.models;
// Generated Oct 25, 2018 2:43:44 PM by Hibernate Tools 3.6.0

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Beacon generated by hbm2java
 */
@Entity
@Table(name = "beacon", catalog = "dealab_db")
public class Beacon implements java.io.Serializable {

	private Long id;
	private Branch branch;
	private String name;
	private Integer type;
	private Integer macAddress;
	private String description;

	public Beacon() {
	}

	public Beacon(Branch branch, String name, Integer type, Integer macAddress, String description) {
		this.branch = branch;
		this.name = name;
		this.type = type;
		this.macAddress = macAddress;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "mac_address")
	public Integer getMacAddress() {
		return this.macAddress;
	}

	public void setMacAddress(Integer macAddress) {
		this.macAddress = macAddress;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
