package com.zinios.dealab.models;
// Generated Oct 25, 2018 2:43:44 PM by Hibernate Tools 3.6.0

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * DealBranch generated by hbm2java
 */
@Entity
@Table(name = "deal_branch", catalog = "dealab_db")
public class DealBranch implements java.io.Serializable {

	private Long id;
	private Deal deal;
	private Branch branch;

	public DealBranch() {
	}

	public DealBranch(Deal deal, Branch branch) {
		this.deal = deal;
		this.branch = branch;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deal_id", nullable = false)
	public Deal getDeal() {
		return this.deal;
	}

	public void setDeal(Deal deal) {
		this.deal = deal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id", nullable = false)
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

}
