package com.zinios.dealab.models;
// Generated Oct 25, 2018 2:43:44 PM by Hibernate Tools 3.6.0

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "dealab_db")
public class Image extends com.avaje.ebean.Model implements java.io.Serializable {

	private Long id;
	private Branch branch;
	private Company company;
	private String url;
	private Integer type;

	public Image() {
	}

	public Image(String url) {
		this.url = url;
	}

	public Image(Branch branch, Company company, String url, Integer type) {
		this.branch = branch;
		this.company = company;
		this.url = url;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "url", nullable = false, length = 2000)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
