package com.zinios.dealab.models;
// Generated Oct 25, 2018 2:43:44 PM by Hibernate Tools 3.6.0

import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * OpenHours generated by hbm2java
 */
@Entity
@Table(name = "open_hours", catalog = "dealab_db")
public class OpenHours extends com.avaje.ebean.Model implements java.io.Serializable {

	private Long id;
	private Branch branch;
	private String day;
	private String hour;

	public OpenHours() {
	}

	public OpenHours(String day, String hour) {
		this.day = day;
		this.hour = hour;
	}

	public OpenHours(Branch branch, String day, String hour) {
		this.branch = branch;
		this.day = day;
		this.hour = hour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "branch_id")
	public Branch getBranch() {
		return this.branch;
	}

	public void setBranch(Branch branch) {
		this.branch = branch;
	}

	@Column(name = "day", nullable = false, length = 25)
	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	@Column(name = "hour", nullable = false, length = 50)
	public String getHour() {
		return this.hour;
	}

	public void setHour(String hour) {
		this.hour = hour;
	}

}
