package com.zinios.dealab.models;
// Generated Oct 25, 2018 2:43:44 PM by Hibernate Tools 3.6.0

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;

import javax.persistence.*;
import java.math.BigDecimal;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "dealab_db", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class User extends com.avaje.ebean.Model implements java.io.Serializable {

	private Long id;
	@JsonIgnoreProperties({"email", "name", "category"})
	private Company company;
	private String name;
	private String email;
	@JsonIgnore
	private String password;
	private String imageUrl;
	private String mobile;
	private BigDecimal homeLat;
	private BigDecimal homeLng;
	private BigDecimal workLat;
	private BigDecimal workLng;
	private Integer loginType;
	private String deviceToken;
	@JsonIgnore
	private String token;
	private String deviceId;

	public User() {
	}

	public User(String name, String email) {
		this.name = name;
		this.email = email;
	}

	public User(Company company, String email) {
		this.company = company;
		this.email = email;
	}

	public User(Company company, String name, String email) {
		this.company = company;
		this.name = name;
		this.email = email;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", length = 1000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "image_url", length = 2000)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "mobile", length = 25)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "home_lat", precision = 15, scale = 10)
	public BigDecimal getHomeLat() {
		return this.homeLat;
	}

	public void setHomeLat(BigDecimal homeLat) {
		this.homeLat = homeLat;
	}

	@Column(name = "home_lng", precision = 15, scale = 10)
	public BigDecimal getHomeLng() {
		return this.homeLng;
	}

	public void setHomeLng(BigDecimal homeLng) {
		this.homeLng = homeLng;
	}

	@Column(name = "work_lat", precision = 15, scale = 10)
	public BigDecimal getWorkLat() {
		return this.workLat;
	}

	public void setWorkLat(BigDecimal workLat) {
		this.workLat = workLat;
	}

	@Column(name = "work_lng", precision = 15, scale = 10)
	public BigDecimal getWorkLng() {
		return this.workLng;
	}

	public void setWorkLng(BigDecimal workLng) {
		this.workLng = workLng;
	}

	@Column(name = "login_type")
	public Integer getLoginType() {
		return this.loginType;
	}

	public void setLoginType(Integer loginType) {
		this.loginType = loginType;
	}

	@Column(name = "device_token", length = 2000)
	public String getDeviceToken() {
		return this.deviceToken;
	}

	public void setDeviceToken(String deviceToken) {
		this.deviceToken = deviceToken;
	}

	@Column(name = "token", length = 1000)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	@Column(name = "device_id")
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}


}
