package com.zinios.dealab.models.entity;
// Generated Oct 25, 2018 2:43:44 PM by Hibernate Tools 3.6.0

import com.avaje.ebean.annotation.Sql;

import javax.persistence.Entity;

/**
 * Reviews generated by hbm2java
 */
@Entity
@Sql
public class Images {

	private String url;

	public Images() {
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}
}
